require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ExploreSafe' do
  config = use_native_modules!

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  pod 'Firebase'
  #pod 'FirebaseUI'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  #pod 'React', :path => '../node_modules/react-native'
  #pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'
  pod 'react-native-restart', :path => '../node_modules/react-native-restart'
  #pod 'TensorFlowLite'
  #pod 'TfliteReactNative', :path => '../node_modules/tflite-react-native/ios'

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  target 'ExploreSafeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ExploreSafe-tvOS' do
  # Pods for ExploreSafe-tvOS

  target 'ExploreSafe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
